### ISSUE TITLE
Request: file, wiki page, or link to site describing output file formats

### ISSUE THREAD

**Issue by holtjma** [Oshlack/STRetch#13]
Hello,

I'm looking into using this software to find some STR expansions in some data we have, but I haven't seen any output explanation in the README or on the wiki.  For example, lets say I have the following line in the *.locus_counts file:

`chr22	47044215	47044882	ATCC	165.2	3`

As I understand it, the line indicates that chr22:470442150-47044882 is a STR of pattern ATCC that has 165.2 repeats of that pattern in the region.  However, I'm not sure what the "3" output means with regard to the sample.  Is it saying that the STR estimation is 3 (as in ATCCATCCATCC)? Or is it saying that the estimation is 3*165.2?  Or am I completely misinterpreting it?  I've also noticed that all of these are integer values and I don't _think_ any of them are less than 1, is that also true?  

Anyways, I don't think I found a page that clearly describes all the fields (if one exists, just point me to the link and I'll close out the ticket), so it'd be great to just have a page that does that.

Thanks in advance!

**Comment by holtjma** [comment]
Just realized that part of the confusion was the fact that I had an error (see issue #14 ) and was missing the STRs.tsv file.  However, looking at the test data, I'm still unsure what the STRs.tsv fields are supposed to be indicating (although I can see they are clearly correlated in this simple test).

**Comment by hdashnow** [comment]
Hi Matt,

Thanks for trying out STRetch! Great suggestion. I've added a page to the wiki describing the files. Take a look and let me know if it needs a bit more detail.

https://github.com/Oshlack/STRetch/wiki/Output-files

**Comment by holtjma** [comment]
Yea, this is great!  Definitely clears up the questions I had regarding the columns in the output.  

One last question about the phrase "with any assigned reads in that sample".  Does this just mean that if a STR doesn't have any assigned reads (i.e., the locuscoverage column is "0"), that it doesn't show up in the file?  I just want to make sure I can make that assumption if I need to downstream.

Thanks for the wiki page!

**Comment by hdashnow** [comment]
Yep, that's exactly right.
