### ISSUE TITLE
stage estimate_size

### ISSUE THREAD

**Issue by martiliasf** [Oshlack/STRetch#20]
After getting all the dependencies installed (hopefully properly), including copying the cluster's Rscript binary into the /tools/bin folder ...... I try to run the included test files and I get this:

```
================================= Stage STR_locus_counts (11_L001) =================================

======================================= Stage estimate_size ========================================
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 10 elements
Calls: ldply -> inherits -> lapply -> FUN -> read.table -> scan
Execution halted
ERROR: Command failed with exit status = 1 : 

/pine/scr/m/a/martyf/STRetch/tools/bin/Rscript /pine/scr/m/a/martyf/STRetch/scripts/estimateSTR.R --model /pine/scr/m/a/martyf/STRetch/scripts/STRcov.model.csv 


========================================= Pipeline Failed ==========================================

Command failed with exit status = 1 : 

/pine/scr/m/a/martyf/STRetch/tools/bin/Rscript /pine/scr/m/a/martyf/STRetch/scripts/estimateSTR.R --model /pine/scr/m/a/martyf/STRetch/scripts/STRcov.model.csv

Use 'bpipe errors' to see output from failed commands. 
```

**Comment by hdashnow** [comment]
Hi @martiliasf,

I've seen similar errors before when using certain versions of the R libraries. Would you be able to let me know the version of R, and the R libraries? I'll see if I can reproduce it.

**Comment by martiliasf** [comment]
I was using r 3.3.1 . My cluster has 3.2.3, 3.4.1, and 3.4.3 available. I will test with the others and see if that mitigates the problem.

i'll have to figure out how to see which versions of the libraries are in these environments... wait, that should be in my home directory... at least the ones I custom installed for this script.... bah, i'll just try loading a different version.

**Comment by martiliasf** [comment]
Changing the R version did nothing.

**Comment by hdashnow** [comment]
STRetch has been updated to use Python for this stage, and no longer requires R. #21

**Comment by hdashnow** [comment]
The new version has additional python dependancies. The easiest way to get these is to delete the whole miniconda folder: 
`STRetch/tools/miniconda`

And remove `STRetch/tools/bin/python`

Then rerun the install script.
