### ISSUE TITLE
Multiple runs of STRetch

### ISSUE THREAD

**Issue by nmmsv** [Oshlack/STRetch#40]
Hello,
Is there a way that I can have multiple instances of STRetch running at the same time?
Currently when I try to run a second instance (while an instance is running in the background), I get the following warning:

```WARNING:  there appears to be a pipeline already running in this directory as process 86970

Running more than one pipeline simultaneously may cause inconsistent results to be returned
or even incorrect files to be used in your pipeline.

Use 'bpipe stop' to stop an existing pipeline if you want to run another one.

Are you sure you want to continue? (y/n):
```

Thanks!

**Comment by hdashnow** [comment]
You can run an additional instance of STRetch in a different working directory. Or you can give multiple sample files to STRetch in the same command for them to be run concurrently if there are sufficient resources. This is especially useful if using a cluster environment, where STRetch can automatically submit jobs for you via bpipe.
