### ISSUE TITLE
Running with Exome Bam

### ISSUE THREAD

**Issue by npatel22526** [Oshlack/STRetch#42]
Hello, 

In the guide there is an example for running WGS samples from BAM , but for exome it shows example with Fastq files only. The same is true pipelines available after installation. 

Would it be OK to edit the "STRetch_exome_pipeline.groovy" to run with the exome ? or it would generate unexpected results. 

Thanks, 
Nick

**Comment by hdashnow** [comment]
Do you mean run the exome pipeline from bam files? Or run the wgs_bam pipeline on exome data?

**Comment by npatel22526** [comment]
run Exome pipeline with Bam files

**Comment by hdashnow** [comment]
I'd have to write some code to handle that case. It's just an issue of normalising for coverage properly.

**Comment by npatel22526** [comment]
Ahh I see. Thanks for quick response. I believe updating the code would take sometime. 
But meanwhile is there is any alternative that you can think of ? I have about 1100 Bams so going from Bam-> Fastq wouldn't be quick. But if that's the option than it can be done. 

Thanks, 
Nick

**Comment by hdashnow** [comment]
It may not be too difficult. I can try to hack something together this afternoon.
The alternative would be to extract all reads with Bazam then stream them in. 
https://github.com/ssadedin/bazam

**Comment by hdashnow** [comment]
Hi @npatel22526 

I've written an exome bam pipeline. Would you like to try it out, and let me know how it works for you?

The code is in this branch:
https://github.com/Oshlack/STRetch/tree/exome_bam

To get it, you can run these commands from the directory where you have installed STRetch:
```
git fetch origin exome_bam:exome_bam
git checkout exome_bam
```

Usage:
```STRetch/tools/bin/bpipe run -p input_regions=all_STRs_in_genome.bed -p EXOME_TARGET=target_region.bed STRetch/pipelines/STRetch_wgs_bam_pipeline.groovy sample1.bam sample2.bam```

Where `all_STRs_in_genome.bed` is a bed file defining the positions of all STRs in the genome, for example hg19.simpleRepeat_period1-6.dedup.sorted.bed. WARNING: using a bed file that only specifies some STRs may cause STRetch to miss expansions, this file must include all STRs in the genome. It must match the reference genome used to produce the bam file, but doesn’t have to match the reference genome used for the rest of the pipeline. 
`target_region.bed` is a bed file specifying the target region of your exome capture.

**Comment by hdashnow** [comment]
Also, if you have any exomes with known expansion in target regions, I'd love to know if it picked them up.

**Comment by npatel22526** [comment]
Wow !! That was very quick. Thank you so much for quick update. I will update you on both how pipeline works as well if it picked up few known expansion that we have.

NIck

**Comment by hdashnow** [comment]
I've pushed an update (accidentally committed my local config files - rookie error)
If you haven't already fetched the exome_bam branch, the above git commands will still work, but if you've already done this you may have to do some git magic to get the updated branch. Let me know if that's the case and I'll let you know the git commands.

**Comment by npatel22526** [comment]
Hello Harriet,
 I didn't use the above command till now so I should be able to use it without issue. Will keep you posted on findings. 

Nick

**Comment by hdashnow** [comment]
@npatel22526 thanks for reporting back.
How long did the mosdepth stage get stuck for? Which stage was it exactly? Was the command still running in the background and just not reporting output?
Could you please try running the mosdepth command directly to see if it works? Look for the last command in `commandlog.txt`. Could you also please paste that command here, so I can see if there are any issues with it?

**Comment by npatel22526** [comment]
I actually left the job running in background so it ran for good 20 hours. It gets stuck after the mosdepth step , as I am seeing the outputs from mosedepth. 

Attached is commandlog.txt file as you can see it's stuck at bwa step
[commandlog.txt](https://github.com/Oshlack/STRetch/files/2635077/commandlog.txt)

The command I ran 
> ~/STRetch/tools/bin/bpipe run -m 8GB -n 1 -p input_regions=hg19.simpleRepeat_period1-6_dedup.sorted.bed -p EXOME_TARGET=SeqCap_EZ_Exome_v2.hg19.bed STRetch_exome_bam_pipeline.groovy INPUT.bam

**Comment by hdashnow** [comment]
Could you please try without the -m and -n flags?

**Comment by npatel22526** [comment]
Yup that solves the issues. 
Thanks
Nick

**Comment by hdashnow** [comment]
Hi Nick,

If you want to use `-n` or `-m` in the future, it's worth noting that `-n` is the number of threads, and STRetch is set to use 8 threads per sample for alignment by default, so if you set `-n` to less than 8 it will simply sit there and not run. Also,` -m` is memory in MB. 
In general, it's not necessary to set `-n` or `-m`. Bpipe will try not to use more resources than are available. The exception to that is when you want to submit a large number of jobs to a cluster, in which case setting '-n' to a large number is generally the best strategy.

**Comment by hdashnow** [comment]
Oops, will leave this issue open until I hear if it's working on your true positives!

**Comment by hdashnow** [comment]
The exome bam pipeline has been merged and is available in the latest version. Let me know if you have any feedback :)

**Comment by npatel22526** [comment]
Hello Harriet,

Sorry for the delayed response.
I was testing for two different STR loci that we knew were expanded. I ran two samples with 1000 other control samples and it worked very well for one of the loci. The sample with expansion had the most significant P-value with the highest outlier score. There were few other samples with significant P-values (i.e < 0.01) but outlier score was half or less than the true one. 
For the second loci it predicted the repeat unit count in normal range, however, also the most significant among the 1000 samples and the highest outlier score.  

There could be couple reasons why it may have not worked, as we would expect it to be,
-	The STR was located in intronic region, it was between two exons (~ 200bp apart), thus we were at least able to recruit reads. 
-	The IGV review suggested that there aren’t any discordant reads.
So I believe it is more of sequencing downside then the algorithm. 

Currently, we are facing high false positive rate (WGS data) where there are too many significant STRs, which can't be true , do you have suggestion on how to reduce it beside outliers scores. 

Best, 
Nick

**Comment by hdashnow** [comment]
That's great to hear that you were able to validate the exome bam pipeline! Thanks sharing your results.

May I ask what you mean by false positives? Have you have tested with PCR or another method and there is no STR expansion there? 
How many significant results are you seeing? Just because an STR is significant, doesn't mean it is disease-causing. I expect there to be many benign STR expansions in each individual.

**Comment by npatel22526** [comment]
Hello Harriet,
I think false positive may not be the right choice of word here. As I mentioned we ran WGS samples and as a negative control we focused on Fragile X loci(https://www.omim.org/entry/608866?search=fra10ac1&highlight=fra10ac1).
Since Fragile X is a rare disease we expected that there shouldn't be many sample with significantly lower P-value but we found about 5% of the samples identified with P-value lower than 10e-40,  outlier score > 13 and bp insertion > 70 (3 bp motif). For this particular case we know that it doesn't cause disease unless affected person have higher than few hundred copies but such information may not be available for all disease causing STRs. 
Given that not all significant expansions are disease causing what would be the best approach to distinguish disease vs non-disease. 

Best,
Nick

**Comment by hdashnow** [comment]
Hi Nick,

The thing to remember here is that STRetch is just reporting variants, not pathogenicity. STRetch has no way of knowing if a particular variant causes disease, it just reports that it is large, and the p value tells you the extent to which it is larger in this particular individual compared to other individuals in the analysis.

As an example, I got a significant hit in the Huntington's Disease locus in one of my samples. This individual hadn't been diagnosed with HD. They were being tested for a completely different condition. So we went back and checked this locus by PCR. Sure enough it was expanded (larger than other individuals anyway) but it was still within the non-pathogenic range for that locus. The individual was not likely to develop HD, thankfully!

What is "normal" for most STR loci is completely unknown. This is something we're still thinking about and trying to get a better base-line for. In the meantime, all we can do is prioritise rare expansions (lower p values) as more likely to be interesting, and then do further analysis. For example looking at disease mechanisms such as relevance of nearby genes to the disease.

Does this help?

Warm regards,
Harriet

**Comment by npatel22526** [comment]
Hello Harriet, 

Yes, the description is really helpful and it makes complete sense. The loci of interest is polymorphic , thus likely more people in normal population will have different number copies of STRs as compare to  what's annotated using reference genome. 
The bottom line is that the best approach to analyze reported results is to prioritize them based on p-values (outliers scores),

Best
Nick
