### ISSUE TITLE
stage estimate_size error with WGS BAM pipeline

### ISSUE THREAD

**Issue by sngo318** [Oshlack/STRetch#53]
I'm trying to run STRetch with the STRetch_wgs_bam_pipeline.groovy pipeline and I get this error:

```

One or more files are missing for sample(s): 89931 89931_500
ERROR: stage estimate_size failed: Command in stage estimate_size failed with exit status = 1 :

PATH=$PATH:/hpf/tools/centos6/STRetch/0.3.1/tools/bin; /hpf/tools/centos6/STRetch/0.3.1/tools/bin/python /hpf/tools/centos6/STRetch/0.3.1/scripts/estimateSTR.py --locus_counts /home/sngo/89931.locus_counts  --STR_counts 89931.STR_counts  --median_cov /home/sngo/89931_500.bwa-0.7.12.markdup.realign.recal.median_cov --model /hpf/tools/centos6/STRetch/0.3.1/scripts/STRcov.model.csv


========================================= Pipeline Failed ==========================================

Command in stage estimate_size failed with exit status = 1 :

PATH=$PATH:/hpf/tools/centos6/STRetch/0.3.1/tools/bin; /hpf/tools/centos6/STRetch/0.3.1/tools/bin/python /hpf/tools/centos6/STRetch/0.3.1/scripts/estimateSTR.py --locus_counts /home/sngo/89931.locus_counts  --STR_counts 89931.STR_counts  --median_cov /home/sngo/89931_500.bwa-0.7.12.markdup.realign.recal.median_cov --model /hpf/tools/centos6/STRetch/0.3.1/scripts/STRcov.model.csv

Use 'bpipe errors' to see output from failed commands.

```

I don't know if the problem is that it's `--STR_counts 89931.STR_counts` and not `--STR_counts /home/sngo/89931.STR_counts`

Any help is appreciated

Thank you

**Comment by hdashnow** [comment]
Hi @sngo318,

Are 89931 and 89931_500 two different samples?

I see a median_cov file for 89931_500, and then the rest of the files refer to 89931.

Just to confirm, you are using the latest version of STRetch? There was a bug in an earlier version where it assumed the sample ID was the first part of the filename before the underscore. If this is the latest version you may have uncovered part 2 of this bug.

**Comment by hdashnow** [comment]
Hi @sngo318,

I'm going to close this for now. Let me know if you're still having this error. I'm happy to investigate further.

Warm regards,
Harriet
