### ISSUE TITLE
Could not read from remote repository.

### ISSUE THREAD

**Issue by sariya** [Oshlack/STRetch#54]
Hi,

I'm trying to install STRetch as instructions provided on github:

```
git clone git@github.com:Oshlack/STRetch.git STRetch
Cloning into 'STRetch'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I can easily clone other github repository, example, hipSTR and don't get timed out error.

**Comment by hdashnow** [comment]
Hi @sariya,

That could be a networking issue. Try cloning the http url:
`git clone https://github.com/Oshlack/STRetch.git`

If that doesn't work you might have to chat to your IT.

Warm regards,
Harriet
