### ISSUE TITLE
locus count step very slow

### ISSUE THREAD

**Issue by hrafehi** [Oshlack/STRetch#55]
Hi,

I have noticed that the locus counts step is often very slow and sometimes seems to get stuck. The log file will show the following output for example:

bpipe.Concurrency	[1]	INFO	|3:03:40 Waiting for 36 parallel stages to complete (pool.active=36 pool.tasks=167) 

I am wondering if this is a resource issue and I need to assign more cores for it to run? I notice that some samples are complete within minutes and then it will get stuck one a few samples that don't seem to finish (even up to a day later) unless I stop the job and restart it.

Thanks!

Haloom

**Comment by hdashnow** [comment]
Hm, that's interesting. I haven't run into that one. Do you want to try it and report back? If it seems to help I can up the default assigned cores.

**Comment by hrafehi** [comment]
I think it might have been a resource issue - the locus count seems to need way more resource than I realised.

**Comment by hdashnow** [comment]
What resources were you giving it when it was running slow and now?

**Comment by hrafehi** [comment]
Initially it was running the locus counts step on all 30 samples on one core and I think 30 gb. This was fine for about 26 of the samples but not the other four. I then ran the locus counts step separately for all samples and gave them one core each - but it still wasn't enough until I increased to 2 cores and 60gb for those four samples.

**Comment by hdashnow** [comment]
Ah, so you're not submitting each parallel stage as a separate job? This is how it's designed to run, letting `bpipe` allocate resources. You can also use the `-n` parameter to limit the number of concurrent threads you'd like it to run.
