### ISSUE TITLE
Interpreting output

### ISSUE THREAD

**Issue by DrMcStrange** [Oshlack/STRetch#58]
Hi,

I'm unsure how the `bpInsertion` and `repeatUnits` fields in the output files should be interpreted in the context of a diploid genotype. Do they represent mean values for the two alleles? Or is it assumed that one allele is reference length, and these are estimates for the other allele?

Thanks for any guidance you can give me.

Best,
Bennet

**Comment by hdashnow** [comment]
Hi Bennet,

The way it's calculated, `bpInsertion` is really the sum of both alleles. In practice one allele is usually close to the reference and the other is expanded, in which case you can just use it to infer the larger allele. But if both are substantially larger than the reference it's not currently possible to distinguish the two alleles. I hope that helps?

Warm regards,
Harriet

**Comment by DrMcStrange** [comment]
Thanks Harriet, that does help. I'm looking at family data, and have come across a couple of cases where both parents have an expanded allele so children may have inherited two expanded alleles. This helps give us an idea of what to look for when genotyping them in the lab.

Cheers,
Bennet
