### ISSUE TITLE
exome_bam_pipeline cram support

### ISSUE THREAD

**Issue by bharatij** [Oshlack/STRetch#60]
Hi Harriet,
I realized that the exome bam pipeline does not support cram files.
I added the following two lines in STRetch_exome_bam_pipeline.groovy  in my copy of STRetch and it is working with cram files. I would like to know if it is correct, and I am wondering if you are planning to add it to the next release.

if(args.any { it.endsWith('.cram') })
    input_type = 'cram'
else
    input_type='bam'

Thanks,
Bharati

**Comment by hdashnow** [comment]
Thanks Bharati! That's an oversight on my part. Would you like to submit a pull request?

**Comment by bharatij** [comment]
Thanks, Harriet for your quick reply. I created a pull request for this change.
