### ISSUE TITLE
Data analysis query

### ISSUE THREAD

**Issue by aakritis0212** [Oshlack/STRetch#72]
Hi Harriet,
It's so nice of you to develop such an easy pipeline for exome data analysis. I'm trying to analyse the data generated by STRetch & I'm not getting any significant p-value with my samples. Also the combined STRs.tsv data is quiet different than sample.tsv data as I'm unable to find the chromosome info in sample_sorted.tsv that is present in STRs.tsv.
Could you please help in data analysis it will be really helpful.

**Comment by hdashnow** [comment]
How many samples are you running? Do any of them have known pathogenic expansions covered by the exome kit target regions? There are relatively few STRs in coding regions compared to the rest of the genome.
If you'd like me to check on the chromosome differences, would you attach an example, or you could email it to me privately at h.dashnow@gmail.com

**Comment by aakritis0212** [comment]
Yes, Sure

**Comment by hdashnow** [comment]
Discussion moved to email :)
